name: .NET Core
 
on: 
    push:
        branches:
            - master
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Build with dotnet
      working-directory: src      
      run: dotnet build --configuration Release
    - name: Publish to Docker
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: geodan/pg2b3dm
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
        workdir: src        
